# Generated by Django 5.1.15 on 2026-06-27 20:58

import accounts.models
import app.BunnyStorage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                storage=app.BunnyStorage.BunnyStorage(),
                upload_to=accounts.models.upload_to_avatar,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="document_number",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="profile",
            name="document_type",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="profile",
            name="state",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
