# Generated by Django 5.1.15 on 2026-06-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_profile_avatar_profile_city_profile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pincode",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
