# Generated by Django 5.1.15 on 2026-06-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="district",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
