# Generated by Django 5.1.15 on 2026-05-21 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('cms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginquiry',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inquiries', to='cms.packagepage'),
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null for guest inquiries; populated once user accounts ship.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to=settings.AUTH_USER_MODEL),
        ),
    ]
