# Generated by Django 5.1.15 on 2026-05-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagepage',
            name='rating',
            field=models.FloatField(default=5.0, help_text='0.0 - 5.0'),
        ),
    ]
