# Generated by Django 5.1.15 on 2026-05-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_packagepage_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsettings',
            name='business_name',
            field=models.CharField(default='Sangam Travels', max_length=120),
        ),
    ]
