# Generated by Django 5.1.15 on 2026-05-28 05:05

import app.BunnyStorage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_contactsettings_business_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostpage',
            name='cover_image_url',
        ),
        migrations.RemoveField(
            model_name='galleryimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='genericpage',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='packagepage',
            name='hero_image_url',
        ),
        migrations.RemoveField(
            model_name='packagereview',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='avatar_url',
        ),
        migrations.AlterField(
            model_name='blogpostpage',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='packagepage',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=''),
        ),
    ]
