# Generated by Django 5.1.15 on 2026-05-28 06:09

import app.BunnyStorage
import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_remove_blogpostpage_cover_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpostpage',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_blog_cover),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_package_gallery),
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_generic_hero),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_home_hero),
        ),
        migrations.AlterField(
            model_name='packagepage',
            name='hero_image',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_package_hero),
        ),
        migrations.AlterField(
            model_name='packagereview',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_package_review_avatar),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_team_photo),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='avatar',
            field=models.ImageField(blank=True, max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_testimonial_avatar),
        ),
    ]
