# Generated by Django 5.1.15 on 2026-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_blogpostpage_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeystop',
            name='x',
        ),
        migrations.RemoveField(
            model_name='journeystop',
            name='y',
        ),
        migrations.AddField(
            model_name='journeystop',
            name='latitude',
            field=models.FloatField(blank=True, help_text='WGS84 latitude, e.g. 27.7172 for Kathmandu', null=True),
        ),
        migrations.AddField(
            model_name='journeystop',
            name='longitude',
            field=models.FloatField(blank=True, help_text='WGS84 longitude, e.g. 85.3240 for Kathmandu', null=True),
        ),
    ]
