# Generated by Django 5.1.15 on 2026-05-29 09:20

import app.BunnyStorage
import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_journeystop_x_remove_journeystop_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystop',
            name='image',
            field=models.ImageField(blank=True, help_text="Photo shown in a lightbox when the user clicks this stop's marker on the map.", max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_journey_stop),
        ),
    ]
