# Generated by Django 5.1.15 on 2026-05-31 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_journeystop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepage',
            name='daily_walking',
            field=models.CharField(blank=True, help_text="e.g. '5–7 hrs'", max_length=80),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='languages',
            field=models.CharField(blank=True, help_text="e.g. 'English, Hindi, Nepali'", max_length=120),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='max_altitude',
            field=models.CharField(blank=True, help_text="e.g. '5,416m (Thorong La)'", max_length=80),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='min_age',
            field=models.CharField(blank=True, help_text="e.g. '14 years'", max_length=40),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='start_end',
            field=models.CharField(blank=True, help_text="e.g. 'Kathmandu / Pokhara'", max_length=120),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='trip_style',
            field=models.CharField(blank=True, help_text="e.g. 'Small-group teahouse trek'", max_length=120),
        ),
    ]
