# Generated by Django 5.1.15 on 2026-05-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_packagepage_daily_walking_packagepage_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepage',
            name='overview_note',
            field=models.TextField(blank=True, help_text='Secondary paragraph under the pull quote in the Overview tab (pace, highlights, etc.). Optional.'),
        ),
    ]
