# Generated by Django 5.1.15 on 2026-05-31 08:25

import app.BunnyStorage
import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_packagepage_overview_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeystop',
            name='panorama',
            field=models.ImageField(blank=True, help_text='Equirectangular 360° photo (2:1 ratio, e.g. 4096×2048). Shown as an interactive panorama when the marker is clicked.', max_length=500, null=True, storage=app.BunnyStorage.BunnyStorage(), upload_to=cms.models.upload_to_journey_stop_panorama),
        ),
        migrations.AddField(
            model_name='journeystop',
            name='panorama_url',
            field=models.URLField(blank=True, help_text="Alternative to uploading: a direct equirectangular 360° image URL (e.g. a Google Drive/Photos direct image link) OR a Google Maps Street View 'embed' iframe URL. Used only when no panorama is uploaded above.", max_length=500),
        ),
    ]
