# Generated by Django 5.1.15 on 2026-05-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_journeystop_panorama_journeystop_panorama_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeystop',
            name='panorama_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading: paste a Google Maps Street View / photo-sphere link (the full maps.google URL) and the 360° image is pulled out automatically. A direct equirectangular image URL also works. Used only when no panorama is uploaded above.', max_length=2000),
        ),
    ]
