# Generated by Django 5.1.15 on 2026-06-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_alter_journeystop_panorama_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagepage',
            name='cutoff_days',
            field=models.PositiveSmallIntegerField(default=14, help_text="Booking closes this many days before a departure's start date."),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='departure_weekdays',
            field=models.CharField(blank=True, help_text="Comma-separated weekdays the auto-calendar seeds departures on. Mon=0 … Sun=6. e.g. '5' = Saturdays. Blank = no auto-calendar (slots seeded on demand).", max_length=20),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='deposit_pct',
            field=models.PositiveSmallIntegerField(default=50, help_text='Percent of total payable as deposit to confirm a seat (e.g. 50).'),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='max_group',
            field=models.PositiveSmallIntegerField(default=18, help_text='Maximum travellers per group/slot.'),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='max_groups_per_date',
            field=models.PositiveSmallIntegerField(default=2, help_text='How many parallel groups (A, B, …) may run on the same date — limited by guides/permits.'),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='min_group',
            field=models.PositiveSmallIntegerField(default=6, help_text='Minimum travellers for a departure to be guaranteed/run.'),
        ),
        migrations.AddField(
            model_name='packagepage',
            name='schedule_weeks_ahead',
            field=models.PositiveSmallIntegerField(default=12, help_text='How many weeks ahead the auto-calendar pre-creates empty departures.'),
        ),
    ]
