# Generated by Django 5.1.15 on 2026-07-26 07:28

import cms.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0013_raise_max_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_blog_cover,
            ),
        ),
        migrations.AlterField(
            model_name="galleryimage",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_package_gallery,
            ),
        ),
        migrations.AlterField(
            model_name="genericpage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_generic_hero,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_home_hero,
            ),
        ),
        migrations.AlterField(
            model_name="journeystop",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Photo shown in a lightbox when the user clicks this stop's marker on the map.",
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_journey_stop,
            ),
        ),
        migrations.AlterField(
            model_name="journeystop",
            name="panorama",
            field=models.ImageField(
                blank=True,
                help_text="Equirectangular 360° photo (2:1 ratio, e.g. 4096×2048). Shown as an interactive panorama when the marker is clicked.",
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_journey_stop_panorama,
            ),
        ),
        migrations.AlterField(
            model_name="packagepage",
            name="hero_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_package_hero,
            ),
        ),
        migrations.AlterField(
            model_name="packagereview",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_package_review_avatar,
            ),
        ),
        migrations.AlterField(
            model_name="teammember",
            name="photo",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_team_photo,
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="avatar",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=cms.models.upload_to_testimonial_avatar,
            ),
        ),
    ]
