# Generated by Django 5.1.15 on 2026-06-25 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0012_packagepage_cutoff_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('group_label', models.CharField(default='A', help_text='A, B, C … for parallel groups on the same date.', max_length=4)),
                ('min_capacity', models.PositiveSmallIntegerField(default=6)),
                ('max_capacity', models.PositiveSmallIntegerField(default=18)),
                ('seats_confirmed', models.PositiveSmallIntegerField(default=0)),
                ('seats_held', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('forming', 'Forming'), ('guaranteed', 'Guaranteed'), ('full', 'Full'), ('locked', 'Locked (cutoff passed)'), ('departed', 'Departed'), ('cancelled', 'Cancelled')], default='forming', max_length=20)),
                ('guaranteed_at', models.DateTimeField(blank=True, null=True)),
                ('cutoff_date', models.DateField(blank=True, null=True)),
                ('price_inr', models.PositiveIntegerField(blank=True, help_text='Per-person price for this departure. Falls back to the package price if blank.', null=True)),
                ('auto_created', models.BooleanField(default=False, help_text='Created by the slotting engine vs. an admin.')),
                ('guide', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='cms.packagepage')),
            ],
            options={
                'ordering': ['start_date', 'group_label'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=200)),
                ('lead_email', models.EmailField(max_length=254)),
                ('lead_phone', models.CharField(blank=True, max_length=40)),
                ('party_size', models.PositiveSmallIntegerField(default=1)),
                ('preferred_start_date', models.DateField(blank=True, null=True)),
                ('date_flexible', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('held', 'Held (awaiting deposit)'), ('confirmed', 'Confirmed (deposit paid)'), ('cancelled', 'Cancelled'), ('expired', 'Hold expired'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('deposit_paid', 'Deposit paid'), ('fully_paid', 'Fully paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('deposit_amount', models.PositiveIntegerField(default=0)),
                ('balance_amount', models.PositiveIntegerField(default=0)),
                ('hold_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='cms.packagepage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slot_bookings', to=settings.AUTH_USER_MODEL)),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='scheduling.departure')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='departure',
            index=models.Index(fields=['package', 'start_date', 'status'], name='scheduling__package_9c5067_idx'),
        ),
        migrations.AddConstraint(
            model_name='departure',
            constraint=models.UniqueConstraint(fields=('package', 'start_date', 'group_label'), name='uniq_departure_group'),
        ),
    ]
