# Generated by Django 5.1.15 on 2026-06-25 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance'), ('refund', 'Refund')], max_length=10)),
                ('merchant_order_id', models.CharField(max_length=64, unique=True)),
                ('phonepe_order_id', models.CharField(blank=True, max_length=80)),
                ('amount', models.PositiveIntegerField(help_text='Amount in paise.')),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='created', max_length=10)),
                ('redirect_url', models.URLField(blank=True, max_length=2000)),
                ('raw_response', models.JSONField(blank=True, help_text='Last status/webhook payload (audit + idempotency).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='scheduling.booking')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
