# Generated by Django 5.1.15 on 2026-06-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending (interested)'), ('accepted', 'Accepted (awaiting deposit)'), ('held', 'Held'), ('confirmed', 'Confirmed (deposit paid)'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20),
        ),
    ]
